### ISSUE TITLE
Number Doors (Curtain Panels)

### ISSUE THREAD

**Issue by dezindzer** [NiWeiNi/BIMiconToolbar#1]
First of all, I love the app, and the icons, and the blog!

_Number doors_ does not work on Curtain Panel doors.

They also should be in the _OST_Doors_ built-in category like the regular doors

![image](https://user-images.githubusercontent.com/77564/145981657-f1b89ff1-5b32-4deb-9987-722999be9b17.png)

**Comment by NiWeiNi** [comment]
Hi @dezindzer, thanks for reporting the issue. 
As far as I know, doors in curtain walls are under the category OST_CurtainWallPanels. Revit considers them panels, otherwise, we won't be able to replace a panel with a 'door'. 

I will take a look into it soon, hopefully, I can expand it to include curtain wall panels by next month.

Cheers!

**Comment by dezindzer** [comment]
Sorry for the late reply.
IDK what happened there.
Must be something specific to that PC. I tried on other PC's and it worked.
